# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20171110_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='account.UserProfile')),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeper', to='account.UserProfile')),
            ],
        ),
    ]
