# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171109_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paid_dues',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grad_year',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('AL', 'Alumni')], max_length=4, null=True),
        ),
    ]
