# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('users', '0005_auto_20171110_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grad_year',
            field=models.IntegerField(choices=[(0, 'Freshman'), (1, 'Sophomore'), (2, 'Junior'), (3, 'Senior'), (4, 'Alumni')], default=1, null=True),
        ),
    ]
