# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='season',
        ),
        migrations.AddField(
            model_name='teammember',
            name='season',
            field=models.ForeignKey(default=2017, on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='game.Season'),
            preserve_default=False,
        ),
    ]
