# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(blank=True, choices=[('Pink', 'Pink'), ('Blue', 'Blue')], max_length=4, null=True),
        ),
    ]
