# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20171206_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='year',
        ),
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(default=2017, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.Season'),
        ),
    ]
