# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_auto_20171206_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statkeepers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_keeper', to='game.Season')),
                ('statkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_keeper', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_keeper', to='game.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='team',
            name='statkeepers',
            field=models.ManyToManyField(related_name='statkeepers', through='game.Statkeepers', to=settings.AUTH_USER_MODEL),
        ),
    ]
