# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20171206_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statkeepers',
            new_name='Statkeeper',
        ),
    ]
