# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20171206_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='week',
        ),
        migrations.AddField(
            model_name='schedule',
            name='weeks',
            field=models.ManyToManyField(through='game.Week', to='game.Game'),
        ),
        migrations.AddField(
            model_name='week',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
            preserve_default=False,
        ),
    ]
