# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-16 04:41
from __future__ import unicode_literals

from django.db import migrations
import game.fields


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_team_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current_season',
            field=game.fields.UniqueBooleanField(default=False),
            preserve_default=False,
        ),
    ]
