# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20171206_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='season',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='weeks',
        ),
        migrations.RemoveField(
            model_name='week',
            name='game',
        ),
        migrations.RemoveField(
            model_name='week',
            name='schedule',
        ),
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
