# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20171206_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.ForeignKey(default=2017, on_delete=django.db.models.deletion.CASCADE, to='game.Season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
