# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20171206_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='playoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
