# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20171206_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='playoff',
            field=models.BooleanField(default=False, verbose_name='Playoff game'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
